export const locations = [
  {
    id: 'can-tho',
    name: 'Cần Thơ',
    type: 'Thành phố trực thuộc Trung ương',
    lat: 10.0452,
    lng: 105.7469,
    intro: 'Địa phương có hoạt động chế biến thủy sản, thực phẩm và các ngành sản xuất phục vụ vùng.',
    cases: [
      {
        id: 'seafood',
        title: 'Chế biến thủy sản',
        label: 'Sản xuất thực phẩm công nghiệp',
        status: 'Hoạt động có dữ liệu công bố',
        summary: 'Sở Khoa học và Công nghệ ghi nhận thủy sản Cần Thơ đạt kim ngạch xuất khẩu hơn 2,1 tỷ USD năm 2025. Đây là số liệu toàn ngành của thành phố, không phải doanh thu của một nhà máy; bài viết cũng nêu quản lý dữ liệu ở một số hợp tác xã còn cần cải thiện.',
        steps: ['Tiếp nhận và kiểm tra nguyên liệu', 'Sơ chế, phân loại và chế biến', 'Bảo quản và đóng gói sản phẩm', 'Kiểm tra chất lượng trước khi xuất hàng'],
        textbook: 'Chương 2 gắn giai cấp công nhân với nền công nghiệp hiện đại và lao động theo phương thức công nghiệp. Khâu chế biến cho thấy người lao động trực tiếp tham gia tạo ra sản phẩm công nghiệp.',
        workerContribution: 'Trong khâu chế biến, công nhân biến thủy sản thành sản phẩm có thể bảo quản và xuất khẩu. Kỹ năng vận hành thiết bị, kiểm soát quy trình và phối hợp giữa các công đoạn góp phần giữ chất lượng và năng suất.',
        promoteRole: 'Đào tạo công nhân về dây chuyền chế biến, bảo quản lạnh, an toàn thực phẩm và kỹ thuật số; tạo điều kiện để họ làm chủ thiết bị và đề xuất cải tiến quy trình.',
        sourceIds: ['cantho-seafood', 'cantho-priorities'],
      },
      {
        id: 'food-processing',
        title: 'Chế biến nông sản',
        label: 'Sản xuất thực phẩm công nghiệp',
        status: 'Ngành được thành phố ưu tiên',
        summary: 'Thành phố muốn phát triển sâu hơn khâu chế biến nông sản và ưu tiên duy trì đất trồng lúa. Cách làm cụ thể tùy từng cơ sở; thẻ này giới thiệu chuỗi công việc thường gặp, không đại diện cho một nhà máy cụ thể.',
        steps: ['Tiếp nhận và phân loại nông sản', 'Làm sạch, sơ chế hoặc chế biến', 'Đóng gói và kiểm tra sản phẩm', 'Lưu kho, đưa ra thị trường'],
        textbook: 'Có thể liên hệ công đoạn chế biến với luận điểm trong Chương 2: công nhân tham gia sản xuất vật chất bằng phương thức công nghiệp.',
        workerContribution: 'Ở khâu chế biến, công nhân trực tiếp vận hành dây chuyền để chuyển nguyên liệu nông nghiệp thành sản phẩm có giá trị cao hơn. Lao động kỹ thuật còn giúp duy trì máy móc, chất lượng và tiến độ sản xuất.',
        promoteRole: 'Gắn đào tạo nghề với thiết bị thực tế; bồi dưỡng kỹ năng vận hành, bảo trì, kiểm soát chất lượng và an toàn. Khuyến khích công nhân tham gia cải tiến để tăng năng suất và giảm hao hụt.',
        sourceIds: ['cantho-priorities'],
      },
      {
        id: 'power-generation',
        title: 'Sản xuất điện khí',
        label: 'Công nghiệp năng lượng',
        status: 'Nhà máy Ô Môn I đã vận hành',
        summary: 'Bài viết của cơ quan TP Cần Thơ ghi nhận Nhà máy Nhiệt điện Ô Môn I đã vận hành cả hai tổ máy từ năm 2015, công suất 660 MW. Không nên nhầm nhà máy này với các dự án Ô Môn khác đang xây dựng hoặc trong quy hoạch.',
        steps: ['Tiếp nhận và kiểm soát nhiên liệu khí', 'Vận hành tua-bin khí và máy phát', 'Theo dõi thông số, thiết bị và an toàn', 'Truyền tải điện lên hệ thống'],
        textbook: 'Chương 2 xem xét vị trí của người lao động trong nền sản xuất công nghiệp hiện đại. Nhà máy điện là ví dụ để liên hệ lao động vận hành kỹ thuật; chi tiết công việc từng vị trí cần nguồn chuyên môn riêng.',
        workerContribution: 'Trong nhà máy điện, các nhóm vận hành, kỹ thuật và bảo dưỡng phối hợp để duy trì thiết bị và nguồn điện ổn định. Đây là phân tích khái quát theo đặc điểm ngành; bài nguồn xác nhận hoạt động của Ô Môn I nhưng không mô tả nhiệm vụ từng vị trí.',
        promoteRole: 'Đào tạo định kỳ về thiết bị điện – khí, tự động hóa, kiểm soát quy trình và an toàn công nghiệp. Tạo điều kiện để người lao động tham gia phát hiện rủi ro, đề xuất cải tiến và cập nhật kỹ năng khi công nghệ thay đổi.',
        sourceIds: ['cantho-omon'],
      },
    ],
  },
  {
    id: 'an-giang',
    name: 'An Giang',
    type: 'Tỉnh',
    lat: 10.5216,
    lng: 105.1259,
    intro: 'Các ví dụ công nghiệp tiêu biểu gồm chế biến cá tra và rau quả đông lạnh.',
    cases: [
      {
        id: 'pangasius',
        title: 'Chế biến cá tra',
        label: 'Sản xuất thực phẩm công nghiệp',
        status: 'Nhà máy và công việc được nêu cụ thể',
        summary: 'Sở Công Thương An Giang mô tả một nhà máy cá tra tại Long Xuyên: công nhân phân loại, làm sạch phi lê và đóng gói để xuất khẩu. Đây là ví dụ hoạt động cụ thể, không phải mô tả mọi cơ sở trong tỉnh.',
        steps: ['Tiếp nhận và kiểm tra cá nguyên liệu', 'Phân loại, làm sạch và cắt phi lê', 'Cấp đông và kiểm tra sản phẩm', 'Đóng gói, bảo quản lạnh và xuất hàng'],
        textbook: 'Sách nói công nhân có thể lao động trực tiếp hoặc gián tiếp với công cụ sản xuất hiện đại. Dây chuyền cá tra cho thấy rõ các vai trò khác nhau trong cùng một quá trình.',
        workerContribution: 'Công nhân tại nhà máy tham gia phân loại, sơ chế phi lê và đóng gói cá tra. Công việc theo dây chuyền giúp sản phẩm đạt quy cách để bảo quản và xuất khẩu; nguồn địa phương nêu trực tiếp các khâu này.',
        promoteRole: 'Đào tạo kỹ thuật chế biến, vận hành và bảo dưỡng thiết bị, kiểm soát vệ sinh và chất lượng. Cải thiện an toàn, điều kiện làm việc và tiếng nói của công nhân để họ gắn bó, nâng tay nghề và phát huy sáng kiến.',
        sourceIds: ['angiang-fish'],
      },
      {
        id: 'fruit',
        title: 'Rau quả và nông sản chế biến',
        label: 'Đa dạng hóa sản phẩm',
        status: 'Hoạt động chế biến được báo cáo',
        summary: 'Sở Công Thương An Giang ghi nhận doanh nghiệp địa phương chế biến rau quả đông lạnh phục vụ xuất khẩu, bên cạnh các mặt hàng truyền thống như gạo và cá tra.',
        steps: ['Tiếp nhận và kiểm tra rau quả', 'Rửa, sơ chế, cắt và phân loại', 'Cấp đông, đóng gói và ghi nhãn', 'Bảo quản lạnh thành phẩm'],
        textbook: 'Khâu cấp đông và đóng gói gắn với sản xuất công nghiệp hiện đại, nơi công nhân phối hợp với thiết bị và kỹ thuật để tạo sản phẩm theo quy cách.',
        workerContribution: 'Trong nhà máy, công nhân sơ chế, cấp đông và đóng gói giúp rau quả giữ chất lượng, đáp ứng quy cách thị trường và kéo dài thời gian bảo quản. Đây là phần đóng góp của lao động công nghiệp trong chuỗi hàng xuất khẩu.',
        promoteRole: 'Nâng kỹ năng vận hành thiết bị lạnh, kiểm soát chất lượng và truy xuất; đào tạo an toàn thực phẩm và an toàn máy móc. Tạo cơ hội học nghề liên tục khi công nghệ và yêu cầu sản phẩm thay đổi.',
        sourceIds: ['angiang-trade'],
      },
      {
        id: 'fish-feed',
        title: 'Sản xuất thức ăn thủy sản',
        label: 'Công nghiệp hỗ trợ nuôi trồng',
        status: 'Nhà máy được Sở Công Thương ghi nhận',
        summary: 'Sở Công Thương An Giang cho biết chuỗi của CLFish có nhà máy thức ăn với công suất thiết kế 56.000 tấn/năm. Đây là công suất thiết kế được công bố, không phải sản lượng thực tế từng năm.',
        steps: ['Kiểm tra và chuẩn bị nguyên liệu', 'Phối trộn theo công thức sản phẩm', 'Ép viên, sấy và kiểm tra chất lượng', 'Đóng gói, lưu kho và xuất hàng'],
        textbook: 'Lĩnh vực này giúp quan sát lao động công nghiệp ở khâu tạo đầu vào cho sản xuất thủy sản. Liên hệ với Chương 2 cần tập trung vào lao động gắn với công cụ và quy trình sản xuất hiện đại.',
        workerContribution: 'Công nhân vận hành các công đoạn chế biến nguyên liệu thành thức ăn; kỹ thuật viên theo dõi chất lượng và thiết bị. Đây là khung phân tích điển hình của ngành, không phải mô tả nhân sự riêng do bài báo cung cấp.',
        promoteRole: 'Bồi dưỡng kỹ năng vận hành dây chuyền, kiểm soát công thức, bảo trì và an toàn; cập nhật kiến thức về chất lượng nguyên liệu. Khuyến khích người lao động tham gia giảm lỗi, tiết kiệm năng lượng và cải tiến quy trình.',
        sourceIds: ['angiang-fish'],
      },
    ],
  },
  {
    id: 'dong-thap',
    name: 'Đồng Tháp',
    type: 'Tỉnh',
    lat: 10.4938,
    lng: 105.6882,
    intro: 'Các ngành hàng dễ nhận ra gồm xay xát lúa gạo, chế biến thủy sản và nông sản.',
    cases: [
      {
        id: 'rice-processing',
        title: 'Xay xát và chế biến gạo',
        label: 'Mắt xích sau thu hoạch',
        status: 'Cơ sở sản xuất được báo chí ghi nhận',
        summary: 'Báo Điện tử Chính phủ từng giới thiệu cơ sở xay xát, chế biến lúa gạo hiện đại tại Đồng Tháp. Ví dụ này cho thấy cách nguyên liệu từ hợp tác xã đi vào dây chuyền chế biến.',
        steps: ['Tiếp nhận và kiểm tra lúa', 'Sấy, làm sạch và tách vỏ', 'Xay xát, đánh bóng và phân loại', 'Đóng bao, lưu kho và giao hàng'],
        textbook: 'Trong Chương 2, công nhân được gắn với lao động bằng phương thức công nghiệp. Dây chuyền xay xát là ví dụ gần gũi để nhận ra máy móc và sự phối hợp của nhiều vị trí.',
        workerContribution: 'Công nhân vận hành các khâu sấy, xay xát, phân loại và đóng bao để biến lúa thành gạo theo quy cách. Sự phối hợp và làm chủ dây chuyền ảnh hưởng trực tiếp đến chất lượng, năng suất và giá trị sản phẩm.',
        promoteRole: 'Bồi dưỡng kỹ năng điều khiển, bảo dưỡng máy và kiểm soát chất lượng; hướng dẫn công nghệ tiết kiệm năng lượng, giảm thất thoát. Kết hợp đào tạo với an toàn lao động và cơ hội đề xuất cải tiến.',
        sourceIds: ['dongthap-rice'],
      },
      {
        id: 'seafood-processing',
        title: 'Chế biến thủy sản',
        label: 'Từ nguyên liệu tới thực phẩm',
        status: 'Ngành chế biến được tỉnh báo cáo',
        summary: 'Cổng thông tin tỉnh Đồng Tháp ghi nhận sản xuất và xuất khẩu thủy sản chế biến của tỉnh. Nguồn cũng nhắc đến yêu cầu về chất lượng và kết nối tiêu thụ.',
        steps: ['Thu mua và kiểm tra nguyên liệu', 'Sơ chế, phân loại và chế biến', 'Đóng gói, bảo quản lạnh', 'Hoàn thiện chứng từ và vận chuyển'],
        textbook: 'Công nhân tham gia tạo sản phẩm và duy trì dây chuyền là phần liên hệ trực tiếp với vai trò kinh tế của giai cấp công nhân trong Chương 2.',
        workerContribution: 'Công nhân tham gia chế biến, đóng gói và bảo quản thủy sản thành sản phẩm có quy cách ổn định. Lao động kỹ thuật giúp dây chuyền hoạt động liên tục và kiểm soát chất lượng.',
        promoteRole: 'Tăng cường đào tạo về máy chế biến, kho lạnh, vệ sinh và kiểm soát chất lượng; bảo đảm an toàn và điều kiện làm việc. Khuyến khích công nhân học kỹ năng mới và tham gia cải tiến sản xuất.',
        sourceIds: ['dongthap-industry'],
      },
      {
        id: 'packaging',
        title: 'Sản xuất bao bì nhựa',
        label: 'Ngành hỗ trợ sản xuất',
        status: 'Ngành công nghiệp có số liệu công bố',
        summary: 'Cổng thông tin tỉnh ghi nhận sản xuất bao bì nhựa tăng 37,5% trong sáu tháng đầu năm 2026. Các bước bên dưới là quy trình thường gặp để người học hình dung; từng nhà máy có thể tổ chức khác nhau.',
        steps: ['Chuẩn bị vật liệu và máy tạo màng', 'In nội dung, màu sắc hoặc ký hiệu', 'Cắt, hàn và hoàn thiện bao bì', 'Kiểm tra kích thước, độ kín và đóng kiện'],
        textbook: 'Sản xuất bao bì cho thấy công nhân vận hành, theo dõi và phối hợp quanh thiết bị công nghiệp để tạo ra sản phẩm phục vụ nhiều ngành.',
        workerContribution: 'Công nhân vận hành máy tạo màng, in, cắt và hàn để tạo bao bì theo yêu cầu; kỹ thuật viên duy trì máy và chất lượng. Sản phẩm này hỗ trợ hoạt động đóng gói của nhiều ngành khác.',
        promoteRole: 'Đào tạo vận hành và bảo trì thiết bị, kiểm soát lỗi và an toàn máy; cập nhật kỹ năng khi tự động hóa thay đổi công việc. Khuyến khích sáng kiến giảm phế phẩm và sử dụng vật liệu hiệu quả.',
        sourceIds: ['dongthap-industry'],
      },
    ],
  },
  {
    id: 'vinh-long',
    name: 'Vĩnh Long',
    type: 'Tỉnh',
    lat: 10.2396,
    lng: 105.9572,
    intro: 'Ngành dừa gắn với vùng nguyên liệu lớn và mạng lưới doanh nghiệp chế biến.',
    cases: [
      {
        id: 'coconut',
        title: 'Dừa và sản phẩm từ dừa',
        label: 'Một trái dừa, nhiều sản phẩm',
        status: 'Ngành hàng chủ lực, có số liệu công bố',
        summary: 'Cổng thông tin tỉnh cho biết Vĩnh Long có vùng trồng dừa lớn và khoảng 180 doanh nghiệp sản xuất, chế biến sản phẩm từ dừa. Sản phẩm gồm nước dừa, sữa dừa, cơm dừa sấy, kẹo và chỉ xơ dừa.',
        steps: ['Tiếp nhận và phân loại dừa', 'Tách nước, cơm, gáo hoặc xơ', 'Chế biến thành các dòng sản phẩm', 'Kiểm tra chất lượng và đóng gói'],
        textbook: 'Ở khâu chế biến, công nhân trực tiếp hoặc gián tiếp vận hành công cụ công nghiệp để tạo ra sản phẩm. Đây là điểm liên hệ của ví dụ này với khái niệm trong Chương 2.',
        workerContribution: 'Ở cơ sở chế biến, công nhân tách và xử lý nguyên liệu để làm ra nước dừa, sữa dừa, cơm dừa sấy hoặc sản phẩm từ xơ. Lao động công nghiệp giúp tăng giá trị nguyên liệu và tạo ra nhiều dòng sản phẩm.',
        promoteRole: 'Đào tạo công nhân về vận hành dây chuyền, kiểm soát chất lượng và bảo trì; hỗ trợ họ tiếp cận công nghệ chế biến mới. Gắn tăng năng suất với an toàn lao động, thu nhập và điều kiện làm việc.',
        sourceIds: ['vinhlong-coconut'],
      },
      {
        id: 'rice',
        title: 'Gạo và bột gạo',
        label: 'Chế biến nguyên liệu tại chỗ',
        status: 'Dự án có giai đoạn vận hành thử',
        summary: 'Cổng xúc tiến đầu tư của tỉnh cho biết một dự án chế biến thực phẩm đã vận hành thử giai đoạn đầu năm 2025, với sản phẩm bột gạo và nông sản sấy. Phần còn lại là kế hoạch nhiều giai đoạn, không nên hiểu là toàn nhà máy đã chạy hết công suất.',
        steps: ['Nhận và làm sạch nguyên liệu', 'Xay thành bột hoặc sơ chế nông sản', 'Sấy, kiểm tra và đóng gói', 'Lưu kho, phân phối sản phẩm'],
        textbook: 'Đây là ví dụ về lao động trong sản xuất vật chất. Cần phân biệt rõ việc một giai đoạn đã vận hành thử với công suất thiết kế của toàn dự án.',
        workerContribution: 'Công nhân vận hành khâu làm sạch, xay, sấy và đóng gói để tạo bột gạo, nông sản sấy. Đóng góp của họ nằm ở việc biến nguyên liệu thành sản phẩm chế biến có thời gian bảo quản và giá trị cao hơn.',
        promoteRole: 'Đào tạo theo đúng dây chuyền và thiết bị đang dùng; nâng kỹ năng vận hành, vệ sinh công nghiệp, kiểm soát chất lượng và an toàn. Tạo lộ trình học nghề khi nhà máy mở rộng công nghệ.',
        sourceIds: ['vinhlong-food'],
      },
      {
        id: 'aquafeed',
        title: 'Thức ăn thủy sản',
        label: 'Đầu vào cho nghề nuôi cá',
        status: 'Nhà máy mới, công suất được công bố',
        summary: 'Báo Điện tử Chính phủ đưa tin nhà máy thức ăn cá biển và cá nước lạnh tại Vĩnh Long mở cửa năm 2026, bổ sung một khâu cung cấp đầu vào cho nuôi trồng thủy sản trong vùng.',
        steps: ['Tiếp nhận và kiểm tra nguyên liệu', 'Phối trộn theo công thức', 'Ép viên, sấy và kiểm tra sản phẩm', 'Đóng bao, lưu kho và giao cho cơ sở nuôi'],
        textbook: 'Có thể quan sát việc công nhân làm chủ máy móc và phối hợp giữa sản xuất, kiểm tra chất lượng và kho vận. Nguồn công bố công suất nhà máy, không phải kết quả đầu ra thực tế.',
        workerContribution: 'Công nhân tham gia tiếp nhận, phối trộn và tạo viên thức ăn thủy sản; kỹ thuật viên kiểm tra chất lượng sản phẩm. Các khâu này tạo đầu vào công nghiệp cho hoạt động nuôi trồng thủy sản.',
        promoteRole: 'Phát triển kỹ năng vận hành dây chuyền, kiểm soát công thức và chất lượng, bảo trì và an toàn. Đào tạo liên tục để công nhân có thể làm chủ thiết bị, phối hợp với kỹ thuật viên và cải tiến quy trình.',
        sourceIds: ['vinhlong-feed'],
      },
    ],
  },
  {
    id: 'ca-mau',
    name: 'Cà Mau',
    type: 'Tỉnh',
    lat: 9.1769,
    lng: 105.1524,
    intro: 'Nhà máy Đạm Cà Mau là ví dụ công nghiệp tiêu biểu tại địa phương.',
    cases: [
      {
        id: 'fertilizer',
        title: 'Nhà máy Đạm Cà Mau',
        label: 'Sản xuất công nghiệp · phân bón',
        status: 'Nhà máy đang hoạt động',
        summary: 'Nhà máy Đạm Cà Mau đạt mốc 11 triệu tấn urê lũy kế vào tháng 12/2024. Một bài báo Chính phủ năm 2024 ghi nhận hơn 1.100 cán bộ, công nhân viên, trong đó có hơn 400 kỹ sư. Đây là ví dụ trực tiếp hơn để tìm hiểu lao động trong sản xuất công nghiệp.',
        steps: ['Nhà máy vận hành dây chuyền công nghiệp', 'Sản xuất urê hạt đục', 'Đội ngũ kỹ sư làm chủ hệ thống', 'Đưa phân bón tới thị trường'],
        textbook: 'Giáo trình gắn giai cấp công nhân với sản xuất công nghiệp hiện đại và người lao động trực tiếp hoặc gián tiếp vận hành công cụ công nghiệp. Cần phân tích theo tiêu chí này, không chỉ nhìn tên nhà máy hay chức danh.',
        workerContribution: 'Công nhân và kỹ sư góp phần vận hành hệ thống sản xuất urê, giữ dây chuyền hoạt động ổn định và tạo ra phân bón phục vụ sản xuất. Báo Chính phủ ghi nhận quy mô đội ngũ năm 2024; không công bố chi tiết từng vị trí.',
        promoteRole: 'Tiếp tục đào tạo để công nhân làm chủ thiết bị và công nghệ, nâng chuyên môn, kỹ năng số và khả năng xử lý sự cố. Đồng thời chú trọng an toàn, cải tiến kỹ thuật và điều kiện để người lao động tham gia xây dựng môi trường làm việc tốt.',
        sourceIds: ['camau-fertilizer', 'camau-fertilizer-workers'],
      },
      {
        id: 'seafood-processing',
        title: 'Chế biến thủy sản · Camimex Xí nghiệp 5',
        label: 'Công nghiệp chế biến thực phẩm',
        status: 'Hồ sơ môi trường phê duyệt dự án nâng công suất · 2022',
        summary: 'Công báo Cà Mau ghi nhận dự án nâng công suất Nhà máy chế biến thủy sản – Xí nghiệp 5 của Camimex Group, công suất dự án 9.120 tấn thành phẩm/năm. Đây là thông tin trong hồ sơ dự án năm 2022, không phải sản lượng hiện nay.',
        steps: ['Tiếp nhận nguyên liệu và phân loại', 'Sơ chế, chế biến và xử lý phụ phẩm', 'Làm lạnh, lưu kho và kiểm tra', 'Đóng gói, bảo quản thành phẩm'],
        textbook: 'Đây là tình huống để vận dụng khái niệm lao động trong sản xuất công nghiệp ở Chương 2. Cần phân biệt hoạt động nuôi tôm với khâu chế biến tại nhà máy khi xác định vai trò người lao động.',
        workerContribution: 'Hồ sơ môi trường nêu các khu vực tiếp nhận nguyên liệu, sơ chế, phân loại, kho lạnh và vận hành thiết bị. Từ các khâu đó có thể liên hệ vai trò của công nhân trong chế biến, bảo quản và giữ vệ sinh quy trình; hồ sơ không đo riêng mức đóng góp của từng vị trí.',
        promoteRole: 'Bồi dưỡng kỹ năng chế biến, vận hành thiết bị lạnh, vệ sinh và kiểm soát chất lượng; bảo đảm an toàn và điều kiện làm việc. Cần tăng khả năng truy xuất nguyên liệu và để công nhân góp ý giảm lỗi, giảm hao hụt.',
        sourceIds: ['camau-seafood'],
      },
      {
        id: 'gas-power',
        title: 'Cụm công nghiệp Khí – Điện',
        label: 'Năng lượng và công nghiệp khí',
        status: 'Cụm công nghiệp đang vận hành',
        summary: 'Báo Điện tử Chính phủ ghi nhận hai nhà máy điện Cà Mau 1 và 2 đã sản xuất lũy kế hơn 100 tỷ kWh. Cụm còn gắn với xử lý khí và sản xuất phân bón; số liệu bài viết phản ánh kết quả tích lũy, không phải sản lượng một năm.',
        steps: ['Tiếp nhận và xử lý khí tự nhiên', 'Cấp khí làm nhiên liệu cho nhà máy điện', 'Vận hành tua-bin và máy phát', 'Giám sát hệ thống, an toàn và môi trường'],
        textbook: 'Cụm sản xuất tích hợp này cho thấy một ví dụ công nghiệp hiện đại với nhiều công đoạn và nhóm nghề kỹ thuật. Chương 2 cung cấp khung lý luận về vị trí của công nhân; bài nguồn cung cấp bối cảnh công nghiệp thực tế.',
        workerContribution: 'Lao động kỹ thuật, vận hành và bảo dưỡng góp phần duy trì các khâu xử lý khí, phát điện và cung ứng sản phẩm. Đây là liên hệ khái quát theo mô hình cụm công nghiệp; không phải số liệu đo đóng góp riêng của công nhân.',
        promoteRole: 'Nâng kỹ năng vận hành hệ thống tích hợp, tự động hóa, bảo trì và ứng phó sự cố; duy trì đào tạo an toàn nghiêm ngặt. Tạo cơ hội để người lao động tham gia cải tiến kỹ thuật và cập nhật công nghệ năng lượng.',
        sourceIds: ['camau-gas-power'],
      },
    ],
  },
];

export const sources = {
  'cantho-priorities': {
    title: 'Cần Thơ tập trung nguồn lực ưu tiên phát triển một số ngành quan trọng',
    publisher: 'Báo Điện tử Chính phủ · 2026',
    url: 'https://baochinhphu.vn/can-tho-tap-trung-nguon-luc-uu-tien-phat-trien-mot-so-nganh-quan-trong-102260530174956211.htm',
  },
  'cantho-seafood': {
    title: 'Thúc đẩy chuyển đổi số để ngành Thủy sản phát triển bền vững',
    publisher: 'Sở Khoa học và Công nghệ thành phố Cần Thơ · 2026',
    url: 'https://sokhcn.cantho.gov.vn/default.aspx?nid=31344&pid=57',
  },
  'cantho-omon': {
    title: 'Kết quả triển khai chiến lược năng lượng tại TP Cần Thơ',
    publisher: 'Ban Tuyên giáo và Dân vận Thành ủy Cần Thơ · 2024',
    url: 'https://btgdv.cantho.gov.vn/vi/news/dua-nghi-quyet-cua-dang-vao-cuoc-song/ket-qua-buoc-dau-trong-trien-khai-thuc-hien-chu-truong-dinh-huong-chien-luoc-phat-trien-nang-luong-quoc-gia-cua-viet-nam-den-nam-2030-tam-nhin-den-nam-2045-o-tp-can-tho-1898.html',
  },
  'angiang-fish': {
    title: 'An Giang tăng tốc xuất khẩu',
    publisher: 'Sở Công Thương tỉnh An Giang · 2026',
    url: 'https://sct.angiang.gov.vn/an-giang-tang-toc-xuat-khau',
  },
  'angiang-trade': {
    title: 'Xuất khẩu An Giang: Từ lợi thế tài nguyên đến năng lực cạnh tranh toàn cầu',
    publisher: 'Sở Công Thương tỉnh An Giang · 2026',
    url: 'https://sct.angiang.gov.vn/xuat-khau-an-giang-tu-loi-tai-nguyen-den-nang-luc-canh-tranh-toan-cau-0',
  },
  'dongthap-rice': {
    title: 'Thủ tướng thăm cơ sở sản xuất, chế biến lúa gạo hiện đại',
    publisher: 'Báo Điện tử Chính phủ · 2023',
    url: 'https://baochinhphu.vn/thu-tuong-tham-mot-so-co-so-san-xuat-che-bien-lua-gao-hien-dai-cong-nghe-cao-102230813124654338.htm',
  },
  'dongthap-industry': {
    title: 'Đồng Tháp tạo điều kiện để doanh nghiệp phát triển',
    publisher: 'Cổng thông tin điện tử tỉnh Đồng Tháp · 2026',
    url: 'https://www.dongthap.gov.vn/tin-tuc/chi-tiet?id=9454080',
  },
  'vinhlong-coconut': {
    title: 'Vĩnh Long phát triển chuỗi giá trị ngành dừa',
    publisher: 'Cổng thông tin điện tử tỉnh Vĩnh Long · 2026',
    url: 'https://portal.vinhlong.gov.vn/portal/wplienhiephoi/lienhiephoi/page/xemtin.cpx?item=6a2687781a3f9b08b3cb1eeb',
  },
  'vinhlong-food': {
    title: 'Dự án nhà máy chế biến nông sản, thực phẩm CPT Food',
    publisher: 'Cổng thông tin xúc tiến đầu tư tỉnh Vĩnh Long · 2025',
    url: 'https://portal.vinhlong.gov.vn/portal/wpipbc/sokhcn/page/xemtin.cpx?item=681dd0471a3f9b886f4a9286',
  },
  'vinhlong-feed': {
    title: 'Nhà máy thức ăn cá biển Vĩnh Long',
    publisher: 'Báo Điện tử Chính phủ · 2026',
    url: 'https://baochinhphu.vn/nha-may-thuc-an-ca-bien-vinh-long.html',
  },
  'camau-fertilizer': {
    title: 'Nhà máy Đạm Cà Mau ghi nhận mốc sản lượng urê',
    publisher: 'Báo Điện tử Chính phủ · 2024',
    url: 'https://baochinhphu.vn/nha-may-dam-ca-mau-can-moc-san-luong-11-trieu-tan-urea-102241225173843434.htm',
  },
  'camau-fertilizer-workers': {
    title: 'Nhân lực và kỹ sư tại Phân bón Cà Mau',
    publisher: 'Báo Điện tử Chính phủ · 2024',
    url: 'https://baochinhphu.vn/phan-bon-ca-mau-hanh-trinh-13-nam-no-luc-va-phat-trien-102240307221108882.htm',
  },
  'camau-seafood': {
    title: 'Công báo Cà Mau số 39: Dự án nâng công suất Nhà máy chế biến thủy sản – Xí nghiệp 5',
    publisher: 'Công báo tỉnh Cà Mau · 2022',
    url: 'https://congbao.camau.gov.vn/Admin/OfficialGazetteStorage/SoCongBao/46815-signed.pdf',
  },
  'camau-gas-power': {
    title: 'Cụm Khí – Điện – Đạm Cà Mau: Hình mẫu công nghiệp trên vùng trũng lầy ven rừng U Minh',
    publisher: 'Báo Điện tử Chính phủ · 2025',
    url: 'https://baochinhphu.vn/cum-khi-dien-dam-ca-mau-hinh-mau-cong-nghiep-tren-vung-trung-lay-ven-rung-u-minh-102251205110416518.htm',
  },
};

export const theory = [
  {
    id: 'worker',
    label: '01 · Khái niệm',
    title: 'Giai cấp công nhân là ai?',
    text: 'Giáo trình gắn giai cấp công nhân với nền công nghiệp hiện đại và cách sản xuất công nghiệp. Người lao động có thể tham gia trực tiếp hoặc gián tiếp vào quá trình ấy. Khi nhìn một nghề cụ thể, hãy hỏi: họ làm gì, ở khâu nào, có tư liệu sản xuất hay phải làm thuê? Cần đủ thông tin rồi mới liên hệ với khái niệm trong sách.',
    takeaway: 'Đừng kết luận chỉ từ tên nghề, nơi làm việc hay việc có dùng máy móc.',
    page: 'Chương 2 · mục 1.1',
  },
  {
    id: 'mission',
    label: '02 · Sứ mệnh',
    title: 'Sứ mệnh lịch sử nói về điều gì?',
    text: 'Theo Chương 2, giai cấp công nhân có vai trò lịch sử trong việc xóa bỏ xã hội tư bản chủ nghĩa và xây dựng xã hội cộng sản chủ nghĩa. Đây là nội dung lý luận rộng hơn chuyện một công nhân vận hành máy hay làm ra một sản phẩm. Ví dụ ở địa phương giúp mình quan sát lao động và sản xuất, còn sứ mệnh cần được học trong bối cảnh xã hội và lịch sử mà giáo trình trình bày.',
    takeaway: 'Không đồng nhất vai trò trong một nhà máy với toàn bộ sứ mệnh lịch sử.',
    page: 'Chương 2 · mục 2',
  },
  {
    id: 'learning',
    label: '03 · Ba mặt',
    title: 'Sứ mệnh có những mặt nào?',
    text: 'Giáo trình phân tích sứ mệnh lịch sử trên ba mặt: kinh tế (tham gia phát triển lực lượng sản xuất và quan hệ sản xuất mới), chính trị – xã hội (giành và sử dụng quyền lực chính trị để cải tạo xã hội), và văn hóa – tư tưởng (xây dựng những giá trị, ý thức mới). Có thể nhớ đây là ba mặt gắn với nhau, không phải ba việc riêng lẻ của từng công nhân.',
    takeaway: 'Khi học, hãy nối từng mặt với lập luận và điều kiện lịch sử trong sách.',
    page: 'Chương 2 · mục 2.2',
  },
];

export const solutions = [
  {
    id: 'skills',
    title: 'Học nghề gắn với công việc thật',
    detail: 'Kết nối trường nghề, doanh nghiệp và người lao động để học đúng thiết bị, quy trình và yêu cầu an toàn.',
    outcome: 'Mở sáng hướng An Giang – Cần Thơ – Vĩnh Long: ưu tiên kỹ năng vận hành, kiểm tra và bảo trì.',
    locationIds: ['an-giang', 'can-tho', 'vinh-long'],
    color: '#f2c566',
  },
  {
    id: 'value-chain',
    title: 'Tăng giá trị sau thu hoạch',
    detail: 'Thử nghiệm thêm khâu sơ chế, bảo quản và chế biến để nông sản có nhiều lựa chọn trước khi bán.',
    outcome: 'Mở sáng hướng Đồng Tháp – An Giang – Vĩnh Long: nối vùng nguyên liệu với nhà máy và kho.',
    locationIds: ['dong-thap', 'an-giang', 'vinh-long'],
    color: '#79d3bd',
  },
  {
    id: 'safe-work',
    title: 'Làm việc an toàn, có tiếng nói',
    detail: 'Đưa an toàn lao động, chất lượng việc làm và ý kiến của người lao động vào kế hoạch phát triển.',
    outcome: 'Mở sáng cả năm địa phương: xem phát triển sản xuất cùng với đời sống của người làm ra sản phẩm.',
    locationIds: locations.map((place) => place.id),
    color: '#f08f72',
  },
  {
    id: 'green',
    title: 'Sản xuất hợp với điều kiện vùng',
    detail: 'Tìm cách tiết kiệm tài nguyên, giảm lãng phí và gìn giữ môi trường ở vùng sông nước, ven biển.',
    outcome: 'Mở sáng hướng Cà Mau – Vĩnh Long – Cần Thơ: đặt sinh thái và sản xuất trong cùng một bài toán.',
    locationIds: ['ca-mau', 'vinh-long', 'can-tho'],
    color: '#a8d276',
  },
];
